---
galaxy_info:
  author: RHDC Network Team
  description: Manage pfSense firewall configuration via REST API and PHP shell
  company: Rodhouse Datacenter
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: pfSense
      versions:
        - 2.7
        - 24.03

  galaxy_tags:
    - networking
    - firewall
    - pfsense
    - dhcp
    - dns

dependencies: []

allow_duplicates: false
