---
galaxy_info:
  role_name: mikrotik
  namespace: rhdc.network
  author: RHDC Infrastructure Team
  description: Configure MikroTik RouterOS switches with 10G trunk and VLAN support
  company: Rodhouse Datacenter
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: RouterOS
      versions:
        - all

  galaxy_tags:
    - networking
    - mikrotik
    - routeros
    - vlan
    - switch
    - storage

dependencies: []

collections:
  - community.routeros
  - ansible.netcommon
