---
# rhdc.network.vlan_bridge role metadata
galaxy_info:
  author: Rodrique Heron
  description: Configure VLAN interfaces and bridges for VM/container networking
  company: Red Hat / Rodhouse Datacenter
  license: Apache-2.0
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"

  galaxy_tags:
    - networking
    - vlan
    - bridge
    - kvm
    - virtualization
    - rhdc

dependencies: []
