---
galaxy_info:
  author: RHDC
  description: Deploy Kea DHCP server with PXE boot support
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"
  galaxy_tags:
    - dhcp
    - kea
    - pxeboot
    - network
    - podman

dependencies: []
